### ISSUE TITLE
Do swc-loader not support sourcemap

### ISSUE THREAD

**Issue by ws456999** [swc-project/swc-loader#14]
Do swc-loader not support sourcemap? i Couldn't find any docs of it in the repo.

Would really appreciate an example of enabling full sourcemaps in Webpack. 

The following is my configuration.

Thank you!

webpack.js
```js
{
        test: /\.tsx?$/,
        exclude: /node_modules/,
        loader: 'swc-loader',
        options: {
           sourceMap: true,
        }
}
```

.swcrc
```js
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es2016"
  }
}
```

**Comment by kdy1** [comment]
I modified the example to use source map.

https://github.com/swc-project/swc-loader/blob/87c3fe6659c4a8b1d27116239a11e8429ad76c96/example/webpack.config.js#L4-L24
