### ISSUE TITLE
Implement caching

### ISSUE THREAD

**Issue by fabiosantoscode** [swc-project/swc-loader#2]
Let's cache these files! A fast compiler is not useful if there's no caching.

**Comment by fabiosantoscode** [comment]
Does anyone want to work on this?

**Comment by fabiosantoscode** [comment]
We can benchmark it before we merge. I think it will be faster, but let's see!

**Comment by marchaos** [comment]
You can already do this with webpack

```
{
      test: /\.(js|jsx|ts|tsx)$/,
      exclude: /node_modules/,
      use: [
          'cache-loader',
          {
              loader: 'swc-loader',
              options: { ... }
          }
      ]
  },
```

as @kdy1 says - not sure it's going to be any faster though.

**Comment by fabiosantoscode** [comment]
Probably not needed then. Closing!
