### ISSUE TITLE
how to use minify?

### ISSUE THREAD

**Issue by green1052** [swc-project/swc-loader#26]
https://webpack.js.org/plugins/terser-webpack-plugin/#swc
https://swc.rs/docs/configuring-swc#minify

Is this right?

**Comment by ZiYuEdward** [comment]
hello did you resolve this problem? i only add minify options in swc-loader but it does't work

**Comment by green1052** [comment]
> hello did you resolve this problem? i only add minify options in swc-loader but it does't work

https://swc.rs/docs/configuration/minification#replacing-terser

**Comment by icy0307** [comment]
Is there any chance I can use `swc-loader` before babel loader in order to minify the code before babel get involved?
