### ISSUE TITLE
sourcemap is not work when use it in npm package!

### ISSUE THREAD

**Issue by ckken** [swc-project/swc-loader#42]
babel-loader 
![image](https://user-images.githubusercontent.com/3890513/159434986-adda358a-bf8c-4316-98e4-2c9e2d7076f7.png)

swc-loader
![image](https://user-images.githubusercontent.com/3890513/159435147-e55474d6-f7ab-49c7-be52-a5ed8ef32872.png)

**Comment by kdy1** [comment]
Did you specify `sourceMaps: true` in `.swcrc`?
Also, I need a reproduction to fix this, in case it's a bug

**Comment by ckken** [comment]
There are files created, but the browser cannot recognize them

**Comment by kdy1** [comment]
Seems like https://github.com/swc-project/swc/issues/2362
