### ISSUE TITLE
0.1.16 breaks Webpack 4

### ISSUE THREAD

**Issue by yazeedbz** [swc-project/swc-loader#44]
Hello,

I believe because of the [new way `0.1.16` accesses the options object](https://github.com/swc-project/swc-loader/commit/4c2c93e09cc92cad0064d3ec2f030d706c821e7f#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L10-R9), apps using Webpack 4 will break.

My app uses Webpack 4 and until I pinned `swc-loader` to `0.1.15`, the `build` task kept returning `this.getOptions is not a function`. So `swc-loader` is receiving the Webpack object just fine, but the jump from 4 to 5 broke this operation.

Is re-adding `loader-utils` a dealer-breaker? This is my first time getting involved in this repo, so I'm not sure what the tradeoffs are.

**Comment by minsoku** [comment]
> 
Hello ,

I had same problem and solve problem

And solved the problem

It's fixed version swc-loader in package.json 

"swc-loader": "^0.1.15" => "swc-loader": "0.1.15"

**Comment by minsoku** [comment]
Hello ,

I had same problem and solve problem

And solved the problem

It's fixed version swc-loader in package.json

"swc-loader": "^0.1.15" => "swc-loader": "0.1.15"

I'm in same enviroment webpack 4

**Comment by yazeedbz** [comment]
@minsoku Yep thanks, that's how I fixed it as well!

However I'm wondering if Webpack 4 users will forever be stuck on `0.1.15`, because of this change in implementation details.

**Comment by kdy1** [comment]
I set `latest` to 0.1.15 and published `0.2.0` instead

**Comment by minsoku** [comment]
> I set `latest` to 0.1.15 and published `0.2.0` instead

감사합니다 ~~

**Comment by yazeedbz** [comment]
> I set `latest` to 0.1.15 and published `0.2.0` instead

Sorry but how does this solve the problem? `0.1.x` --> `0.2.x` is a minor bump, which shouldn't contain breaking changes.

**Comment by kdy1** [comment]
@yazeedbz No It's not a minor bump

**Comment by yazeedbz** [comment]
@kdy1 From [the semver docs](https://semver.org/), it seems changes that break users' apps is a _major_ change (`1.x.x` --> `2.x.x`)

<img width="1218" alt="semver" src="https://user-images.githubusercontent.com/95372772/163228595-9b59f16d-6c68-41bb-a320-19d23457f12f.png">


* [Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.](https://semver.org/#spec-item-6)
* [Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API.](https://semver.org/#spec-item-7)

**Comment by kdy1** [comment]
It's bit different for 0.x
Read it fully

2022년 4월 14일 (목) 오전 1:40, yazeedbz ***@***.***>님이 작성:

**Comment by yazeedbz** [comment]
Oh man you're right...I'm sorry about that 😓 

* Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Thanks for patiently clarifying!
