### ISSUE TITLE
Import unnamed resources

### ISSUE THREAD

**Issue by duncanbeevers** [swc-project/swc-loader#6]
`@babel/helper-module-imports` permits import statements with no identifier to establish dependencies between files without exposing a javascript expression for that import.

https://babeljs.io/docs/en/babel-helper-module-imports

Common usage looks like
```js
import 'bootstrap';
```

swc / swc-loader doesn't recognize this form of import statement, and throws.

```
Module parse failed: Unexpected token
```

### Expected behavior
A dependency should be established between the parent and referenced file; no javascript expression representing the imported resource should be generated.

**Comment by kdy1** [comment]
@duncanbeevers I think correct syntax is `import 'bootstrap';`. Isn't it?
Babel's documentation also say `import 'bootstrap';` is correct.

**Comment by duncanbeevers** [comment]
Yes, that's right. I've corrected the description to reflect this.

**Comment by kdy1** [comment]
Codegen of side-effect imports was wrong.
`import 'sideeffect'` is converted to `import  from 'sideeffect';` I'll fix it soon
