### ISSUE TITLE
Babel plugin support with SWC?

### ISSUE THREAD

**Issue by hans-bala-glean** [swc-project/swc-loader#71]
Working on a team of 200 and successfully migrated from Babel to SWC with 2x speed boost. Absolutely loving SWC 🚀 

We're looking to support internationalization using the [fbt](https://github.com/facebook/fbt) library. They seem to be tightly coupled with Babel.
Based on these issues: https://github.com/facebook/fbt/issues/392, https://github.com/facebook/fbt/discussions/349 it seems like they've punted it to the OS community.

My question is two fold:
+ Does there exist some kind of middleware that allows direct usage of babel plugins while keeping some of the speed benefits of SWC (the reason I ask is because I came across https://github.com/swc-project/swc/issues/2175)?
+ In the future, for the community, I expect multiple libraries to not support / have wasm based plugins. In a lot of cases, it would be much easier to import / transfer a babel based JS plugin to an SWC one. Judging by https://swc.rs/docs/plugin/ecmascript/getting-started, it seems like we only support WASM based plugins?

**Comment by hrasoa** [comment]
https://github.com/facebook/fbt/discussions/349
