### ISSUE TITLE
[Question] swc-loader bundle size

### ISSUE THREAD

**Issue by Steven19Lee** [swc-project/swc-loader#76]
Hi, currently I want to replace babel with SWC for speeding up my project. I change my babel-loader to swc-loader, it make speed faster, but it also makes my bundle size bigger ( increase from 132MB to 174MB ), I want to ask is this behavior is normal or maybe there are somthing i can configure to make my bundle size smaller , thank ~

my babelrc config :

<img width="524" alt="babel-config" src="https://user-images.githubusercontent.com/67428009/236426687-1496920b-2c92-4682-8a34-62c3a8d87233.png">

my webpack loader config:

<img width="524" alt="loader-config" src="https://user-images.githubusercontent.com/67428009/236426731-55bfa024-d7b5-489b-be94-de4e2d847ceb.png">

bundle size change : 
- with babel
<img width="273" alt="original" src="https://user-images.githubusercontent.com/67428009/236426796-fd52e6fe-2eae-416f-988f-a8ff88f87357.png">
- with swc:
<img width="273" alt="new-folder" src="https://user-images.githubusercontent.com/67428009/236426866-7387b68f-bb5f-4101-97f1-78b41d47fa20.png">

**Comment by kdy1** [comment]
It's not expected, but you need to provide a repro

**Comment by Steven19Lee** [comment]
Hi @kdy1  thanks for your reply, since this repo this private to my company, I would try my best to create a repo to reproduce the problem if possible, I will leave some comments if I reproduce is created, thanks
